/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prouast_heartbeat_RPPGMobile */

#ifndef _Included_com_prouast_heartbeat_RPPGMobile
#define _Included_com_prouast_heartbeat_RPPGMobile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_prouast_heartbeat_RPPGMobile
 * Method:    _initialise
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_prouast_heartbeat_RPPGMobile__1initialise
  (JNIEnv *, jclass);

/*
 * Class:     com_prouast_heartbeat_RPPGMobile
 * Method:    _load
 * Signature: (JLcom/prouast/heartbeat/RPPGMobile/RPPGListener;IIDIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_com_prouast_heartbeat_RPPGMobile__1load
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jdouble, jint, jint, jstring, jstring, jstring, jstring, jboolean, jboolean);

/*
 * Class:     com_prouast_heartbeat_RPPGMobile
 * Method:    _processFrame
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_prouast_heartbeat_RPPGMobile__1processFrame
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     com_prouast_heartbeat_RPPGMobile
 * Method:    _exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_prouast_heartbeat_RPPGMobile__1exit
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
