/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prouast_heartbeat_RPPGSimple */

#ifndef _Included_com_prouast_heartbeat_RPPGSimple
#define _Included_com_prouast_heartbeat_RPPGSimple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_prouast_heartbeat_RPPGSimple
 * Method:    _initialise
 * Signature: (Lcom/prouast/heartbeat/RPPGSimple/RPPGListener;IIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_prouast_heartbeat_RPPGSimple__1initialise
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jstring, jstring, jstring, jstring, jboolean, jboolean);

/*
 * Class:     com_prouast_heartbeat_RPPGSimple
 * Method:    _processFrame
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_prouast_heartbeat_RPPGSimple__1processFrame
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     com_prouast_heartbeat_RPPGSimple
 * Method:    _exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_prouast_heartbeat_RPPGSimple__1exit
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
