/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prouast_heartbeat_FFmpegEncoder */

#ifndef _Included_com_prouast_heartbeat_FFmpegEncoder
#define _Included_com_prouast_heartbeat_FFmpegEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_prouast_heartbeat_FFmpegEncoder
 * Method:    _initialise
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_prouast_heartbeat_FFmpegEncoder__1initialise
  (JNIEnv *, jclass);

/*
 * Class:     com_prouast_heartbeat_FFmpegEncoder
 * Method:    _openFile
 * Signature: (JLjava/lang/String;IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_prouast_heartbeat_FFmpegEncoder__1openFile
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jint);

/*
 * Class:     com_prouast_heartbeat_FFmpegEncoder
 * Method:    _writeFrame
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_prouast_heartbeat_FFmpegEncoder__1writeFrame
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_prouast_heartbeat_FFmpegEncoder
 * Method:    _closeFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_prouast_heartbeat_FFmpegEncoder__1closeFile
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
