/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prouast_heartbeat_RPPG_RPPGAlgorithm */

#ifndef _Included_com_prouast_heartbeat_RPPG_RPPGAlgorithm
#define _Included_com_prouast_heartbeat_RPPG_RPPGAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
