/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prouast_heartbeat_RPPGSimple_RPPGListener */

#ifndef _Included_com_prouast_heartbeat_RPPGSimple_RPPGListener
#define _Included_com_prouast_heartbeat_RPPGSimple_RPPGListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
